[workspace]
resolver = "2"

members = [
    "roman_to_int",
    "longest_common_prefix",
    "single_thread_tasker",
    "build_array_with_stack",
    "median_two_arrays",
    "regex_pattern",
    "generate_parentheses",
    "longest_palindrome",
    "first_last_sorted",
]
